export default [
  {
    id: 0,
    title: "My personal website",
    description: "",
    image: "images/MeScreenS.png",
    url: "http://me.kipriecken.com",
    specs: [
      "Served with Nginx",
      "Hosted on DigitalOcean",
      "SSL Certified",
      "Golang backend",
      "PostgreSQL database",
      "Created using SvelteJS",
      "Responsive",
      "Bootstrap formatting",
      "Formspree contact form",
    ],
  },
  {
    id: 1,
    title: "Bilingual Musician Site",
    description: "",
    image: "images/Roman.png",
    url: "https://romanyearian.netlify.app",
    specs: [
      "Created with SvelteJS",
      "Bilingual with svelte-i18n",
      "Responsive",
      "Bootstrap formatting",
    ],
  },
  {
    id: 2,
    title: "Photography site for myself",
    description: "",
    image: "images/myphotos.png",
    url: "https://photosbykip.netlify.app",
    specs: ["Created using SvelteJS", "Responsive", "Bootstrap formatting"],
  },
  {
    id: 3,
    title: "Blackjack",
    description: "",
    image: "images/blackjack.png",
    url: "https://compassionate-wozniak-c359a2.netlify.app/",
    specs: ["Vanilla JS", "Responsive", "Pure CSS", "jQuery"],
  },
  {
    id: 4,
    title: "Baby Name Generator",
    description: "",
    image: "images/BabyName.png",
    url: "https://whattonamemybaby.netlify.app/",
    specs: ["Responsive", "Bootstrap formatting", "Pulls from API"],
  },
  {
    id: 5,
    title: "Responsive Advent Calendar",
    description: "",
    image: "images/AdventScreenS.png",
    url: "https://adventcal.netlify.app",
    specs: [
      "Created using SvelteJS",
      "Responsive",
      "Bootstrap formatting",
      "Date-responsive",
    ],
  },
  {
    id: 6,
    title: "Sam Pederson Photography",
    description: "",
    image: "images/SamScreenS.png",
    url: "https://sampedersenphotography.netlify.app",
    specs: ["Created using SvelteJS", "Responsive", "Bootstrap formatting"],
  },
  {
    id: 7,
    title: "2020 US elections Voting Info",
    description: "",
    image: "images/VotingScreenS.png",
    url: "https://usvotingapp2020.herokuapp.com/",
    specs: ["Responsive", "Bootstrap formatting", "Pulls from API"],
  }

];
