export default [
  {
    id: 0,
    title: "Sam Pederson Photography",
    description: "",
    image: "images/SamScreenS.png",
    url: "https://sampedersenphotography.netlify.app",
    specs: ["Created using SvelteJS", "Responsive", "Bootstrap formatting"],
  },
  {
  id: 1,
      title: "My personal website",
      description: "",
      image: "images/MeScreenS.png",
      url: "http://me.kipriecken.com",
      specs: ["Served with Nginx", "Hosted on DigitalOcean", "Golang backend", "PostgreSQL database", "Created using SvelteJS", "Responsive", "Bootstrap formatting", "Functioning contact form"]
  },
  {
    id: 2,
    title: "2020 US elections Voting Info",
    description: "",
    image: "images/VotingScreenS.png",
    url: "https://usvotingapp2020.herokuapp.com/",
    specs: ["Responsive", "Bootstrap formatting", "Pulls from API"],
  },
  {
    id: 3,
    title: "Responsive Advent Calendar",
    description: "",
    image: "images/AdventScreenS.png",
    url: "https://adventcal.netlify.app",
    specs: ["Created using SvelteJS", "Responsive", "Bootstrap formatting"],
  },
  {
    id: 4,
    title: "Baby Name Generator",
    description: "",
    image: "images/BabyScreenS.png",
    url: "https://whatshouldinamemybaby.herokuapp.com/",
    specs: ["Responsive", "Bootstrap formatting", "Pulls from API"],
  },
  {
    id: 5,
    title: "Bilingual Musician Site",
    description: "",
    image: "images/Roman.png",
    url: "https://romanyearian.netlify.app",
    specs: ["Created with SvelteJS", "Bilingual with svelte-i18n","Responsive", "Bootstrap formatting"],
  },
];
